- .editorconfig
- .eslintrc.json
- .prettierrc
- libs/cc-components/src/lib/CcComponents.tsx
- package-lock.json
- package.json
Initial ESlint and Prettier configuration for project.
Completes: AB#30605
Completes: AB#30610
> [General] - chore: init eslint and prettier

- .github/workflows/ci.yml
- .github/workflows/main.yml
-   [x] New feature (non-breaking change which adds functionality) …
> chore: initial ci workflow

- .github/workflows/ci.yml
> chore: add set shas docs

- package.json
Add lint-all command to easily lint every project.
-   [ ] …
> chore: add lint command for all projects

- libs/handoverapp/src/lib/utils-garden/getProgressKey.ts
- libs/punchapp/src/lib/config/filterConfig.ts
- libs/punchapp/src/lib/types/punch.ts
- libs/punchapp/src/lib/utils-garden/fieldSettings.ts
- libs/punchapp/src/lib/utils-garden/getDateKey.ts
- libs/punchapp/src/lib/utils-garden/getHighlightedColumn.ts
- libs/shared/src/lib/types/fieldSettings.ts
> chore: garden and filter configs

- libs/handoverapp/src/lib/config/index.ts
- libs/handoverapp/src/lib/config/tableConfig.tsx
- libs/handoverapp/src/lib/types/handoverPackage.ts
- libs/shared/src/lib/components/index.ts
First table config for handover app
-   [ ] Documentation and …
> [libs/handoverapp] - feat: table config

- .github/workflows/ci.yml
- libs/shared/src/lib/components/table/cells/YearAndWeekCell.tsx
- libs/shared/src/lib/components/table/cells/index.ts
- libs/shared/src/lib/utils-dates/toDate.ts
- libs/workorderapp/src/lib/config/index.ts
- libs/workorderapp/src/lib/config/tableConfig.tsx
- libs/workorderapp/src/lib/utils-statuses/getMatStatusColorByStatus.ts
- libs/workorderapp/src/lib/utils-statuses/getMccrStatusColorByStatus.ts
- libs/workorderapp/src/lib/utils-statuses/index.ts
- package-lock.json
- package.json
First version of workorder table config.
-   [ ] Documentation and …
> [libs/workorderapp] - feat: workorder table config

- libs/workorderapp/src/lib/utils-statuses/followup/getFollowUpStatus.ts
> [libs/workorder] - fix: add m12 to yield mat & wo available status

- libs/swcrapp/src/lib/utils-garden/fieldSettings.ts
- libs/workorderapp/src/lib/ui-garden/Item.tsx
- libs/workorderapp/src/lib/utils-garden/fieldSettings.ts
- package-lock.json
- package.json
> feat: update to new workspace fusion

- libs/shared/src/lib/components/sidesheet/index.ts
- libs/shared/src/lib/components/sidesheet/sidesheet.styles.ts
- libs/shared/src/lib/components/sidesheet/tabs/details/details.styles.ts
- libs/shared/src/lib/components/sidesheet/tabs/details/index.ts
- libs/shared/src/lib/components/sidesheet/tabs/details/stringCell.ts
- libs/shared/src/lib/components/sidesheet/tabs/index.ts
- libs/shared/src/lib/components/sidesheet/tabs/material/AvailableItemCell.tsx
- libs/shared/src/lib/components/sidesheet/tabs/material/MaterialTab.tsx
- libs/shared/src/lib/components/sidesheet/tabs/material/columns.tsx
- libs/shared/src/lib/components/sidesheet/tabs/material/index.ts
- libs/shared/src/lib/components/sidesheet/tabs/material/types.ts
- libs/shared/src/lib/components/sidesheet/tabs/mccr/MccrTab.tsx
- libs/shared/src/lib/components/sidesheet/tabs/mccr/columns.tsx
- libs/shared/src/lib/components/sidesheet/tabs/mccr/index.ts
- libs/shared/src/lib/components/sidesheet/tabs/mccr/types.ts
- libs/shared/src/lib/components/table/TabTable/TabTable.tsx
- libs/workorderapp/src/lib/ui-sidesheet/DetailsTab.tsx
- libs/workorderapp/src/lib/ui-sidesheet/WorkorderSidesheet.tsx
Initial sidesheet component for workorder. Will be changed once sidesheet component is ready from fusion-workspace.
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] I have linked my DevOps task …
> [libs/workorderapp] - feat: workorder sidesheet init

- libs/loopapp/src/lib/config/gardenConfig.ts
- libs/loopapp/src/lib/config/workspaceConfig.ts
- libs/loopapp/src/lib/ui-garden/Item.tsx
- libs/loopapp/src/lib/ui-garden/Popover.tsx
- libs/loopapp/src/lib/ui-garden/garden.styles.ts
- libs/loopapp/src/lib/ui-garden/index.ts
- libs/loopapp/src/lib/utils-garden/fieldSettings.ts
- libs/loopapp/src/lib/utils-garden/getItemWidth.ts
- libs/loopapp/src/lib/utils-garden/index.ts
> [libs/loop] - feat: garden config for loop

- apps/handover/app-manifest.json
- apps/handover/package.json
> [handover] - feat: add manifest for fusion app and scripts for publish

- apps/swcr/.browserslistrc
- apps/swcr/.eslintrc.json
- apps/swcr/package.json
- apps/swcr/project.json
- apps/swcr/src/main.tsx
- apps/swcr/tsconfig.app.json
- apps/swcr/tsconfig.json
- apps/swcr/vite.config.ts
- libs/shared/src/lib/components/table/cells/DescriptionCell.tsx
- libs/swcrapp/src/lib/config/filterConfig.tsx
- libs/swcrapp/src/lib/config/gardenConfig.tsx
- libs/swcrapp/src/lib/config/index.ts
- libs/swcrapp/src/lib/config/statusBarConfig.ts
- libs/swcrapp/src/lib/config/tableConfig.tsx
- libs/swcrapp/src/lib/config/workspaceConfig.tsx
- libs/swcrapp/src/lib/index.ts
- libs/swcrapp/src/lib/ui-garden/Grouped.tsx
- libs/swcrapp/src/lib/ui-garden/Header.tsx
- libs/swcrapp/src/lib/ui-garden/Item.tsx
- libs/swcrapp/src/lib/ui-garden/garden.styles.ts
- libs/swcrapp/src/lib/ui-garden/index.ts
- libs/swcrapp/src/lib/utils-garden/customDescription.ts
- libs/swcrapp/src/lib/utils-garden/getItemWidth.ts
- libs/swcrapp/src/lib/utils-statuses/index.ts
- libs/swcrapp/src/lib/utils-statuses/sortPackagesByStatusAndNumber.ts
> [SWCR] - feat: init swcr app with fusion framework and workspace

- libs/handoverapp/src/lib/config/workspaceConfig.ts
> [libs/handoverapp] - chore: change contextid

- .github/workflows/ci.yml
- libs/handoverapp/src/lib/config/workspaceConfig.tsx
- libs/loopapp/src/lib/config/workspaceConfig.tsx
- libs/mechanicalcompletionapp/src/lib/config/workspaceConfig.tsx
- libs/swcrapp/src/lib/config/workspaceConfig.tsx
- libs/workorderapp/src/lib/config/workspace.tsx
- package.json
- pnpm-lock.yaml
> chore: update workspace and add default tabs

- libs/handoverapp/src/lib/config/contextConfig.ts
- libs/handoverapp/src/lib/config/gardenConfig.ts
- libs/handoverapp/src/lib/config/responseConfig.ts
- libs/handoverapp/src/lib/config/workspaceConfig.tsx
- libs/handoverapp/src/lib/ui-garden/Item.tsx
- libs/handoverapp/src/lib/utils-garden/getDateKey.ts
- libs/handoverapp/src/lib/utils-garden/getFieldKeyBasedOnPlannedForecast.ts
- libs/handoverapp/src/lib/utils-garden/getHighlightedColumn.ts
- libs/handoverapp/src/lib/utils-garden/getItemWidth.ts
- libs/loopapp/src/lib/ui-garden/Item.tsx
- libs/mechanicalcompletionapp/src/lib/config/contextConfig.ts
- libs/mechanicalcompletionapp/src/lib/config/gardenConfig.tsx
- libs/mechanicalcompletionapp/src/lib/config/responseConfig.ts
- libs/mechanicalcompletionapp/src/lib/config/workspaceConfig.tsx
- libs/mechanicalcompletionapp/src/lib/ui-garden/Item.tsx
- libs/swcrapp/src/lib/config/responseConfig.ts
- libs/swcrapp/src/lib/config/workspaceConfig.tsx
- libs/swcrapp/src/lib/ui-garden/Item.tsx
- libs/workorderapp/src/lib/ui-garden/Item.tsx
- package-lock.json
- package.json
> chore: update workspace fusion and fix errors

- apps/handover/README.md
- apps/mechanicalcompletion/README.md
- apps/workorder/README.md
> [docs] - chore: add docs to mc, wo, handover

- .github/workflows/post-pr.yml
Add post pr to teams
-   [ ] Documentation and comments is added …
> feat: post pr to teams

- apps/handover/app-manifest.json
- apps/handover/package.json
Bumping version for handover. Releasing new version to Fusion app store locally.
> [apps/handover] -  chore: bump handover versions

- apps/handover/app-manifest.json
- apps/handover/package.json
> [apps/handover] - chore: bump handover version and release

- apps/handover/README.md
> [apps/handover] - Update README.md

- apps/handover/app-manifest.json
- apps/handover/package.json
> [apps/handover] - chore: bump handover

- libs/handoverapp/src/lib/config/filterConfig.tsx
- libs/handoverapp/src/lib/config/tableConfig.tsx
- libs/shared/src/lib/components/StatusSquare.tsx
- libs/shared/src/lib/components/index.ts
- libs/shared/src/lib/components/sidesheet/tabs/ncr/columns.tsx
- libs/shared/src/lib/components/sidesheet/tabs/punch/columns.tsx
- libs/shared/src/lib/components/sidesheet/tabs/query/columns.tsx
- libs/shared/src/lib/components/sidesheet/tabs/swcr/columns.tsx
- libs/shared/src/lib/components/sidesheet/tabs/tabs.styles.ts
- libs/shared/src/lib/components/sidesheet/tabs/unsignedAction/columns.tsx
- libs/shared/src/lib/components/sidesheet/tabs/unsignedTask/columns.tsx
- libs/shared/src/lib/components/sidesheet/tabs/workorder/columns.tsx
- libs/shared/src/lib/components/table/cells/DescriptionCell.tsx
- libs/shared/src/lib/components/table/cells/cell.styles.ts
Visual improvements to handover and shared library components.
Completes: [AB#34323](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/34323)
-   [x] New feature (non-breaking change which adds functionality)
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code.
- …
> [libs/handoverapp & libs/shared] - chore: visual improvements to handover

- apps/handover/app-manifest.json
- apps/handover/package.json
> [apps/handover] - chore: bump handover 0.0.7

- libs/handoverapp/src/lib/ui-garden/GroupBy.tsx
- package-lock.json
- package.json
> chore: bump dependencies

- apps/loop/project.json
- apps/loop/src/main.tsx
- apps/mechanicalcompletion/src/main.tsx
- apps/punch/src/main.tsx
- apps/swcr/src/main.tsx
- apps/workorder/project.json
- apps/workorder/src/main.tsx
- libs/handoverapp/src/lib/config/workspaceConfig.tsx
- libs/loopapp/src/lib/config/frameworkConfig.ts
- libs/loopapp/src/lib/config/index.ts
- libs/loopapp/src/lib/config/workspaceConfig.tsx
- libs/mechanicalcompletionapp/src/lib/config/frameworkConfig.ts
- libs/mechanicalcompletionapp/src/lib/config/index.ts
- libs/mechanicalcompletionapp/src/lib/config/workspaceConfig.tsx
- libs/punchapp/src/lib/config/frameworkConfig.ts
- libs/punchapp/src/lib/config/index.ts
- libs/punchapp/src/lib/config/workspaceConfig.tsx
- libs/swcrapp/src/lib/config/frameworkConfig.ts
- libs/swcrapp/src/lib/config/index.ts
- libs/swcrapp/src/lib/config/workspaceConfig.tsx
- libs/workorderapp/src/lib/config/frameworkConfig.ts
- libs/workorderapp/src/lib/config/index.ts
- libs/workorderapp/src/lib/config/workspace.tsx
> [apps] - chore: context selection in apps

- apps/workorder/app-manifest.json
- apps/workorder/package.json
- apps/workorder/vite.config.ts
> [apps/workorder] - fix: add env plugin for workorder

- apps/workorder/app-manifest.json
- apps/workorder/package.json
> [apps/workorder] - chore: bump to 0.0.3

- apps/handover/package.json
- apps/handover/project.json
- apps/loop/package.json
- apps/loop/project.json
- apps/mechanicalcompletion/package.json
- apps/mechanicalcompletion/project.json
- apps/punch/package.json
- apps/punch/project.json
- apps/swcr/package.json
- apps/swcr/project.json
- apps/workorder/package.json
- apps/workorder/project.json
fusion-framework-cli build app causes GA to fail, switching to tsc instead temporarliy.
> [apps] - chore: update failing build scripts for app

- apps/handover/src/main.tsx
- apps/mechanicalcompletion/src/main.tsx
- apps/punch/src/main.tsx
- apps/swcr/src/main.tsx
- apps/workorder/src/main.tsx
- libs/plugins/src/generators/fusion-app-generator/files/src/main.tsx__template__
- libs/shared/src/lib/hooks/useResourceData.ts
- package-lock.json
- package.json
Use the new react query package
> chore: update dep to tanstack query

- libs/shared/src/lib/hooks/index.ts
- libs/shared/src/lib/hooks/useContextTitle.ts
- libs/shared/src/lib/hooks/usePBIHelpers.ts
- libs/shared/src/lib/hooks/useServiceDiscovery.ts
> [shared] - feat: add pbi helper hook

- libs/shared/src/lib/hooks/usePBIHelpers.ts
> [shared] - fix: update token type

- libs/handoverapp/src/lib/config/workspaceConfig.tsx
- libs/mechanicalcompletionapp/src/lib/config/workspaceConfig.tsx
- libs/workorderapp/src/lib/config/workspace.tsx
> refactor: :recycle: refactor querykey for refetching

- libs/checklistapp/tsconfig.lib.json
- libs/preservationanalyticsapp/tsconfig.lib.json
- tsconfig.base.json
> chore:  add new libs to tsconfig and remove wrong template code

- libs/ccoverviewapp/tsconfig.lib.json
- tsconfig.base.json
> chore: add missing path and remove template error from ccoverview

- libs/workorderapp/src/lib/config/workspace.tsx
> feat: :sparkles: Added workorder analytics tab

- apps/query/.eslintrc.json
- apps/query/README.md
- apps/query/app-manifest.json
- apps/query/package.json
- apps/query/project.json
- apps/query/src/main.tsx
- apps/query/tsconfig.app.json
- apps/query/tsconfig.json
- apps/query/vite.config.ts
- libs/queryapp/.babelrc
- libs/queryapp/.eslintrc.json
- libs/queryapp/README.md
- libs/queryapp/package.json
- libs/queryapp/project.json
- libs/queryapp/src/index.ts
- libs/queryapp/src/lib/config/frameworkConfig.ts
- libs/queryapp/src/lib/config/index.ts
- libs/queryapp/src/lib/config/workspaceConfig.tsx
- libs/queryapp/src/lib/index.ts
- libs/queryapp/tsconfig.json
- libs/queryapp/tsconfig.lib.json
- tsconfig.base.json
Completes: [AB#35657](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/35657)
-   [ ] My code follows the style guidelines of this …
> feat: :sparkles: Added query analytics

- apps/loop/app-manifest.json
- apps/loop/package.json
- apps/loop/vite.config.ts
Adding ENV to vite config for loop
> [loop] - fix: add env to loop vite config

- apps/loop/src/main.tsx
Switch from react-query to the new tanstack/react-query
> [Loop] - chore: use tanstack query for loop

- apps/swcr/app-manifest.json
- apps/swcr/package.json
- apps/swcr/vite.config.ts
> [swcr] - fix: plugin for vite

- apps/ccoverview/app-manifest.json
- apps/ccoverview/package.json
- apps/checklist/app-manifest.json
- apps/checklist/package.json
- apps/handover/app-manifest.json
- apps/handover/package.json
- apps/loop/app-manifest.json
- apps/loop/package.json
- apps/mechanicalcompletion/app-manifest.json
- apps/mechanicalcompletion/package.json
- apps/preservationanalytics/app-manifest.json
- apps/preservationanalytics/package.json
- apps/punch/app-manifest.json
- apps/punch/package.json
- apps/query/app-manifest.json
- apps/query/package.json
- apps/swcr/app-manifest.json
- apps/swcr/package.json
- apps/workorder/app-manifest.json
- apps/workorder/package.json
- libs/handoverapp/src/lib/config/workspaceConfig.tsx
- libs/shared/src/lib/hooks/usePBIOptions.ts
- libs/swcrapp/src/lib/config/workspaceConfig.tsx
- package-lock.json
- package.json
> chore: update deps and app versions

- libs/shared/src/lib/hooks/usePBIHelpers.ts
- libs/shared/src/lib/types/index.ts
- libs/shared/src/lib/types/powerbi.ts
> feat: :sparkles: expand powerbi utils

- apps/jcainstallation/.eslintrc.json
- apps/jcainstallation/README.md
- apps/jcainstallation/app-manifest.json
- apps/jcainstallation/package.json
- apps/jcainstallation/project.json
- apps/jcainstallation/src/main.tsx
- apps/jcainstallation/tsconfig.app.json
- apps/jcainstallation/tsconfig.json
- apps/jcainstallation/vite.config.ts
- libs/handoverapp/src/lib/config/workspaceConfig.tsx
- libs/jcainstallationapp/.babelrc
- libs/jcainstallationapp/.eslintrc.json
- libs/jcainstallationapp/README.md
- libs/jcainstallationapp/package.json
- libs/jcainstallationapp/project.json
- libs/jcainstallationapp/src/index.ts
- libs/jcainstallationapp/src/lib/config/frameworkConfig.ts
- libs/jcainstallationapp/src/lib/config/index.ts
- libs/jcainstallationapp/src/lib/config/workspaceConfig.tsx
- libs/jcainstallationapp/src/lib/index.ts
- libs/jcainstallationapp/tsconfig.json
- libs/jcainstallationapp/tsconfig.lib.json
- libs/punchapp/src/lib/config/workspaceConfig.tsx
- tsconfig.base.json
> feat: :sparkles: Added JCA installation and changed Punch PBI id

- apps/jcainstallation/app-manifest.json
Update to correct fusion manifest.
> [Installation ] - chore: update manifest

- apps/jcainstallation/package.json
Update appkey for deploy script.
> [Installation] - chore: update deploy script

- apps/commissioningtask/.eslintrc.json
- apps/commissioningtask/README.md
- apps/commissioningtask/app-manifest.json
- apps/commissioningtask/package.json
- apps/commissioningtask/project.json
- apps/commissioningtask/src/main.tsx
- apps/commissioningtask/tsconfig.app.json
- apps/commissioningtask/tsconfig.json
- apps/commissioningtask/vite.config.ts
- libs/commissioningtaskapp/.babelrc
- libs/commissioningtaskapp/.eslintrc.json
- libs/commissioningtaskapp/README.md
- libs/commissioningtaskapp/package.json
- libs/commissioningtaskapp/project.json
- libs/commissioningtaskapp/src/index.ts
- libs/commissioningtaskapp/src/lib/config/frameworkConfig.ts
- libs/commissioningtaskapp/src/lib/config/index.ts
- libs/commissioningtaskapp/src/lib/config/workspaceConfig.tsx
- libs/commissioningtaskapp/src/lib/index.ts
- libs/commissioningtaskapp/tsconfig.json
- libs/commissioningtaskapp/tsconfig.lib.json
- tsconfig.base.json
Completes: [AB#35787](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/35787)
-   [ ] My code follows the style guidelines of this …
> feat: :sparkles: Added commissioning task

- apps/jcaworkpreparation/.eslintrc.json
- apps/jcaworkpreparation/README.md
- apps/jcaworkpreparation/app-manifest.json
- apps/jcaworkpreparation/package.json
- apps/jcaworkpreparation/project.json
- apps/jcaworkpreparation/src/main.tsx
- apps/jcaworkpreparation/tsconfig.app.json
- apps/jcaworkpreparation/tsconfig.json
- apps/jcaworkpreparation/vite.config.ts
- libs/jcaworkpreparationapp/.babelrc
- libs/jcaworkpreparationapp/.eslintrc.json
- libs/jcaworkpreparationapp/README.md
- libs/jcaworkpreparationapp/package.json
- libs/jcaworkpreparationapp/project.json
- libs/jcaworkpreparationapp/src/index.ts
- libs/jcaworkpreparationapp/src/lib/config/frameworkConfig.ts
- libs/jcaworkpreparationapp/src/lib/config/index.ts
- libs/jcaworkpreparationapp/src/lib/config/workspaceConfig.tsx
- libs/jcaworkpreparationapp/src/lib/index.ts
- libs/jcaworkpreparationapp/tsconfig.json
- libs/jcaworkpreparationapp/tsconfig.lib.json
- tsconfig.base.json
> feat: :sparkles: Added jca work preparation

- apps/preservationanalytics/app-manifest.json
- apps/preservationanalytics/package.json
> chore: :lipstick: changed name of preservation in manifest

- apps/ccoverview/app-manifest.json
- apps/ccoverview/package.json
- apps/checklist/app-manifest.json
- apps/checklist/package.json
- apps/commissioningtask/app-manifest.json
- apps/commissioningtask/package.json
- apps/handover/app-manifest.json
- apps/handover/package.json
- apps/jcainstallation/app-manifest.json
- apps/jcainstallation/package.json
- apps/loop/app-manifest.json
- apps/loop/package.json
- apps/mechanicalcompletion/app-manifest.json
- apps/mechanicalcompletion/package.json
- apps/query/app-manifest.json
- apps/query/package.json
- apps/swcr/app-manifest.json
- apps/swcr/package.json
- apps/workorder/app-manifest.json
- apps/workorder/package.json
> [apps] - chore: bump version

- libs/shared/src/lib/components/powerbi/ReportMeta.tsx
- package-lock.json
- package.json
> fix: :bug: powerbi popover close

- libs/shared/src/lib/components/powerbi/ReportMeta.tsx
> feat: :sparkles: add mailto

- apps/ccoverview/app-manifest.json
- apps/ccoverview/package.json
- apps/checklist/app-manifest.json
- apps/checklist/package.json
- apps/mechanicalcompletion/app-manifest.json
- apps/mechanicalcompletion/package.json
Update to apps' latest versions.
> [apps] - chore: updated to latest version

- libs/punchshared/tsconfig.json
- libs/punchshared/tsconfig.lib.json
- libs/punchsidesheet/tsconfig.json
- libs/punchsidesheet/tsconfig.lib.json
Remove spec which came from old template.
> [libs/punch] - chore: remove old template from punch

- package-lock.json
- package.json
> fix: make storybook work for windows

- apps/jcaspools/.eslintrc.json
- apps/jcaspools/README.md
- apps/jcaspools/app-manifest.json
- apps/jcaspools/package.json
- apps/jcaspools/project.json
- apps/jcaspools/src/main.tsx
- apps/jcaspools/tsconfig.app.json
- apps/jcaspools/tsconfig.json
- apps/jcaspools/vite.config.ts
- libs/jcaspoolsapp/.eslintrc.json
- libs/jcaspoolsapp/README.md
- libs/jcaspoolsapp/package.json
- libs/jcaspoolsapp/project.json
- libs/jcaspoolsapp/src/index.ts
- libs/jcaspoolsapp/src/lib/config/frameworkConfig.ts
- libs/jcaspoolsapp/src/lib/config/index.ts
- libs/jcaspoolsapp/src/lib/config/workspaceConfig.tsx
- libs/jcaspoolsapp/src/lib/index.ts
- libs/jcaspoolsapp/tsconfig.json
- libs/jcaspoolsapp/tsconfig.lib.json
- libs/jcaspoolsapp/vite.config.ts
- tsconfig.base.json
> feat: :sparkles: Added JCA spools analyics

- libs/plugins/src/generators/app-library/generator.ts
> [shared/plugins] - fix: update project.json template for libs

- apps/jcaspools/app-manifest.json
- apps/jcaspools/package.json
Updating name and key according to Fusion App.
> [apps/spools] - chore: update names and key for spools

- apps/loop/app-manifest.json
- apps/loop/package.json
> [apps/loop] - fix: loop bundle

- libs/shared/src/lib/stories/SidesheetTable.stories.tsx
> chore: storybook change

- .github/workflows/storybook.yml
- libs/shared/src/lib/stories/Sidesheet.stories.tsx
- package.json
> chore: try something with gp and sb

- .github/workflows/storybook.yml
- libs/shared/src/lib/stories/Sidesheet.stories.tsx
> chore: try something with sb

- apps/activities/.eslintrc.json
- apps/activities/README.md
- apps/activities/app-manifest.json
- apps/activities/package.json
- apps/activities/project.json
- apps/activities/src/main.tsx
- apps/activities/tsconfig.app.json
- apps/activities/tsconfig.json
- apps/activities/vite.config.ts
- libs/activitiesapp/.eslintrc.json
- libs/activitiesapp/README.md
- libs/activitiesapp/package.json
- libs/activitiesapp/project.json
- libs/activitiesapp/src/index.ts
- libs/activitiesapp/src/lib/config/frameworkConfig.ts
- libs/activitiesapp/src/lib/config/index.ts
- libs/activitiesapp/src/lib/config/workspaceConfig.tsx
- libs/activitiesapp/src/lib/index.ts
- libs/activitiesapp/tsconfig.json
- libs/activitiesapp/tsconfig.lib.json
- libs/activitiesapp/vite.config.ts
- tsconfig.base.json
> feat: :sparkles: Added activities analytics

- apps/activities/project.json
- apps/ccoverview/project.json
- apps/checklist/project.json
- apps/commissioningtask/project.json
- apps/handover/project.json
- apps/jcainstallation/project.json
- apps/jcaspools/project.json
- apps/jcaworkpreparation/project.json
- apps/loop/project.json
- apps/preservationanalytics/project.json
- apps/punch/project.json
- apps/query/project.json
- apps/swcr/project.json
- apps/workorder/project.json
- package.json
- tools/projectsWithPBITag.js
- tools/projectsWithWSTag.js
> [WIP] - feat: script for only bumping pbi and ws apps

- apps/jcainstallation/CHANGELOG.md
- apps/jcainstallation/app-manifest.json
- apps/jcainstallation/package.json
- apps/jcainstallation/vite.config.ts
- package-lock.json
- package.json
> [apps/jcainstallation] - chore: test new rollup inject plugin

- libs/handoversidesheet/src/lib/ui-sidesheet/HandoverSidesheet.tsx
- libs/mechanicalcompletionsidesheet/src/lib/ui-sidesheet/McSidesheet.tsx
- libs/punchsidesheet/src/lib/ui-sidesheet/PunchSidesheet.tsx
- libs/shared/src/lib/components/sidesheet/Header/Header.tsx
- libs/swcrsidesheet/src/lib/ui-sidesheet/SwcrSidesheet.tsx
- libs/workordersidesheet/src/lib/ui-sidesheet/WorkorderSidesheet.tsx
Add new sidesheet header design, and implement it on workorder
Completes: [AB#36247](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/36247)
-   [ …
> [Shared/Workorder] chore: add new sidesheet header design

- apps/handover/package.json
- apps/loop/package.json
- apps/mechanicalcompletion/package.json
- apps/preservationanalytics/CHANGELOG.md
- apps/preservationanalytics/app-manifest.json
- apps/preservationanalytics/package.json
- apps/swcr/package.json
- apps/workorder/package.json
> chore: release and fix build

- apps/tags/.eslintrc.json
- apps/tags/CHANGELOG.md
- apps/tags/README.md
- apps/tags/app-manifest.json
- apps/tags/package.json
- apps/tags/project.json
- apps/tags/src/main.tsx
- apps/tags/tsconfig.app.json
- apps/tags/tsconfig.json
- apps/tags/vite.config.ts
- libs/tagsapp/.eslintrc.json
- libs/tagsapp/README.md
- libs/tagsapp/package.json
- libs/tagsapp/project.json
- libs/tagsapp/src/index.ts
- libs/tagsapp/src/lib/config/frameworkConfig.ts
- libs/tagsapp/src/lib/config/index.ts
- libs/tagsapp/src/lib/config/workspaceConfig.tsx
- libs/tagsapp/src/lib/index.ts
- libs/tagsapp/tsconfig.json
- libs/tagsapp/tsconfig.lib.json
- libs/tagsapp/vite.config.ts
- tsconfig.base.json
> feat: :sparkles: Added tags analytics

- apps/tags/app-manifest.json
> [apps/tags] - fix: tags name in app manifest

- apps/activities/project.json
- libs/plugins/src/generators/fusion-app-generator/generator.ts
> [libs/plugins] - fix: typo executor

- libs/plugins/src/generators/fusion-app-generator/files/CHANGELOG.md__template__
- libs/plugins/src/generators/fusion-app-generator/files/vite.config.ts__template__
> [libs/plugins] - chore: update template for app generator

- libs/plugins/src/generators/fusion-app-generator/files/vite.config.ts__template__
> [libs/plugins] - chore: update app gen template

- libs/shared/common/.storybook/main.js
- libs/shared/common/.storybook/tsconfig.json
- libs/shared/sidesheet/.storybook/main.js
- libs/shared/sidesheet/.storybook/tsconfig.json
- libs/shared/table-helpers/.storybook/main.js
- libs/shared/table-helpers/.storybook/tsconfig.json
- libs/storybook-host/.storybook/main.js
- libs/storybook-host/.storybook/tsconfig.json
- libs/storybook-host/package.json
- libs/storybook-host/tsconfig.lib.json
- libs/storybook-host/vite.config.ts
- nx.json
> [storybook] - chore: cleanup

- libs/shared/common/.storybook/main.js
- libs/shared/sidesheet/.storybook/main.js
- libs/shared/table-helpers/.storybook/main.js
- libs/storybook-host/.storybook/main.js
> fix: tsconfig paths for storybook

- libs/shared/sidesheet/src/lib/sidesheet/Header/Header.tsx
fix sidesheet header ellipsis and close button
-   [ ] …
> chore: fix sidesheet header ellipsis and close button

- apps/punch/package.json
> [apps/punch]- chore: update npm script for building

- README.md
- apps/docs/src/consts.ts
- apps/docs/src/content/docs/development/tldr.md
Section about common commands in the project.
> [apps/docs] - chore: add section about common commands

- apps/docs/src/content/docs/development/creating-an-app.md
- apps/docs/src/content/docs/development/tldr.md
Adding info about how to get new lines in changelog from cli.
> [docs] - chore: add info about new lines in changelog

- apps/workorder/CHANGELOG.md
- apps/workorder/app-manifest.json
- apps/workorder/package.json
- apps/workorder/src/main.tsx
- libs/workorderapp/src/lib/config/frameworkConfig.ts
- libs/workorderapp/src/lib/config/tableConfig.tsx
- libs/workorderapp/src/lib/config/workspace.tsx
- libs/workordershared/src/lib/types/workorder.ts
- libs/workordersidesheet/src/lib/ui-sidesheet/WorkorderSidesheet.tsx
- libs/workordersidesheet/src/lib/utils-sidesheet/useMaterial.ts
- libs/workordersidesheet/src/lib/utils-sidesheet/useMccr.ts
A WIP for frontend fetching data from CC App api
> [workorder] - feat: WIP Workorder app api

- apps/activities/package.json
- apps/ccoverview/package.json
- apps/checklist/package.json
- apps/commissioningtask/package.json
- apps/handover/package.json
- apps/jcainstallation/package.json
- apps/jcaspools/package.json
- apps/jcaworkpreparation/package.json
- apps/loop/package.json
- apps/mechanicalcompletion/package.json
- apps/preservationanalytics/package.json
- apps/punch/package.json
- apps/query/package.json
- apps/swcr/package.json
- apps/tags/package.json
- apps/workorder/package.json
- libs/plugins/src/generators/fusion-app-generator/files/package.json__template__
- package-lock.json
- package.json
Update fusion cli with new fusion endpoints and bypass bug with main path
> chore: update fusion cli and fix main packagejson

- apps/workorder/app-manifest.json
- apps/workorder/package.json
- libs/workorderapp/package.json
- pnpm-lock.yaml
> Publish: workorder 1.0.3

- apps/loop/CHANGELOG.md
- apps/loop/app-manifest.json
- apps/loop/package.json
> chore: :bookmark: publish loop@0.1.1

- apps/workorder/CHANGELOG.md
- apps/workorder/app-manifest.json
- apps/workorder/package.json
- libs/workorderapp/package.json
- package.json
- pnpm-lock.yaml
> chore: :bookmark: publish workorder@1.0.6

- libs/loopapp/src/lib/config/tableConfig.tsx
- libs/punchapp/src/lib/config/tableConfig.tsx
- libs/shared/src/packages/workspace-config/src/useGridDataSource.ts
- libs/workorderapp/src/lib/config/tableConfig.tsx
- turbo.json
> fix grid rowcount loop punch workorder

- apps/handover/package.json
- package.json
- pnpm-lock.yaml
> fix: :bug: fix url mismatch portal

- libs/handoverapp/src/lib/config/workspaceConfig.tsx
- libs/loopapp/src/lib/config/workspaceConfig.tsx
- libs/mechanicalcompletionapp/src/lib/config/workspaceConfig.tsx
- libs/powerbiapp/src/Report.tsx
- libs/punchapp/src/lib/config/workspaceConfig.tsx
- libs/scopechangerequestapp/src/lib/config/workspaceConfig.tsx
- libs/swcrapp/src/lib/config/workspaceConfig.tsx
- libs/workorderapp/src/lib/config/workspace.tsx
> fix: :bug: invalidate on contextid change

- libs/shared/src/packages/workspace-config/src/useGridDataSource.ts
> fix: :bug: ag grid fail to load rows error

- libs/shared/src/packages/data-proxy/index.ts
- libs/shared/src/packages/data-proxy/src/components/GenericUnauthorizedPage.tsx
> feat: add generic unauthorized page

- libs/loopsidesheet/src/lib/ui-sidesheet/LoopSidesheet.tsx
- libs/workordersidesheet/src/lib/ui-sidesheet/WorkorderSidesheet.tsx
> chore: remove 3d tabs in sidesheets

- apps/handover/app.config.js
- apps/loop/app.config.js
- apps/mechanicalcompletion/app.config.js
- apps/punch/app.config.js
- apps/swcr/app.config.js
- apps/workorder/app.config.js
- apps/workorder/package.json
- libs/handoverapp/src/lib/config/frameworkConfig.ts
- libs/loopapp/src/lib/config/frameworkConfig.ts
- libs/mechanicalcompletionapp/src/lib/config/frameworkConfig.ts
- libs/punchapp/src/lib/config/frameworkConfig.ts
- libs/swcrapp/src/lib/config/frameworkConfig.ts
- libs/workorderapp/src/lib/config/frameworkConfig.ts
> feat: :sparkles: configure envs for apps

- libs/handoverapp/src/lib/config/tableConfig.tsx
- libs/loopapp/package.json
- libs/mechanicalcompletionapp/src/lib/config/tableConfig.tsx
- libs/punchapp/package.json
- libs/scopechangerequestapp/src/lib/config/tableConfig.tsx
- libs/shared/package.json
- libs/shared/src/packages/table-helpers/src/lib/table/TabTable/TabTable.tsx
- libs/swcrapp/src/lib/config/tableConfig.tsx
- libs/workorderapp/package.json
- pnpm-lock.yaml
> feat: :sparkles: reduce bundle size (11MB) -> (6MB) grid

- libs/handoverapp/src/lib/config/frameworkConfig.ts
- libs/shared/src/packages/table-helpers/src/lib/table/TabTable/TabTable.tsx
- libs/shared/src/packages/workspace-config/src/defaultColDef.ts
> fix: :bug: fix multiple grid instances crashing

- libs/shared/src/packages/workspace-config/src/defaultGridOptions.tsx
> chore: add initial row count: 100

- libs/workordersidesheet/src/lib/ui-sidesheet/DetailsTab.tsx
> fix: remove duplicate data in sidesheet

- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/mc/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/mccr/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/ncr/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/punch/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/query/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/swcr/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/unsignedAction/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/unsignedTask/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/workorder/columns.tsx
> chore: comment out procosysurls

- apps/handover/package.json
- libs/shared/src/packages/hooks/src/lib/useContextId.ts
> chore: change context id from id to externalid

- libs/punchapp/src/lib/config/tableConfig.tsx
> fix: implement autosize columns

- libs/loopapp/src/lib/config/workspaceConfig.tsx
- libs/punchapp/src/lib/config/workspaceConfig.tsx
- libs/shared/src/packages/cc-api/index.ts
- libs/shared/src/packages/cc-api/useCCApiAccessCheck.ts
- libs/shared/src/packages/index.ts
- libs/shared/src/packages/loading/components/CCApiAccessLoading.tsx
- libs/shared/src/packages/loading/index.ts
- libs/workorderapp/src/lib/config/workspace.tsx
> feat: :sparkles: access check

- libs/handoversidesheet/src/lib/ui-sidesheet/HandoverSidesheet.tsx
- libs/loopapp/src/lib/config/tableConfig.tsx
- libs/loopsidesheet/src/lib/ui-sidesheet/Checklists.tsx
- libs/loopsidesheet/src/lib/ui-sidesheet/LoopContentTable.tsx
- libs/loopsidesheet/src/lib/ui-sidesheet/LoopSidesheet.tsx
- libs/mechanicalcompletionapp/src/lib/config/tableConfig.tsx
- libs/mechanicalcompletionsidesheet/src/lib/ui-sidesheet/McSidesheet.tsx
- libs/punchapp/src/lib/config/tableConfig.tsx
- libs/punchsidesheet/src/lib/ui-sidesheet/PunchSidesheet.tsx
- libs/swcrapp/src/lib/config/tableConfig.tsx
- libs/swcrsidesheet/src/lib/ui-sidesheet/SwcrSidesheet.tsx
- libs/workorderapp/src/lib/config/tableConfig.tsx
- libs/workordersidesheet/src/lib/ui-sidesheet/WorkorderSidesheet.tsx
> fix: comment out all procosys URLs

- libs/punchapp/src/lib/config/tableConfig.tsx
- libs/scopechangerequestapp/src/lib/config/tableConfig.tsx
- package.json
- pnpm-lock.yaml
> fix: format dates

- libs/workorderapp/src/lib/config/tableConfig.tsx
> fix(workorder): remove duplicate column

- libs/handoverapp/package.json
- pnpm-lock.yaml
> chore: alpha.6.0

- libs/shared/src/packages/table-helpers/src/lib/table/TabTable/TabTable.tsx
- libs/workordersidesheet/src/lib/ui-sidesheet/WorkorderSidesheet.tsx
- libs/workordersidesheet/src/lib/utils-sidesheet/useMaterial.ts
- libs/workordersidesheet/src/lib/utils-sidesheet/useMccr.ts
> fix(Workorder):/material mccr error

- libs/loopapp/src/lib/config/gardenConfig.ts
- libs/loopapp/src/lib/config/tableConfig.tsx
- libs/loopapp/src/lib/config/workspaceConfig.tsx
- libs/punchapp/src/lib/config/gardenConfig.ts
- libs/punchapp/src/lib/config/tableConfig.tsx
- libs/punchapp/src/lib/config/workspaceConfig.tsx
- libs/shared/src/packages/error-boundary/src/components/errors/CCApiUnauthorized.tsx
- libs/shared/src/packages/workspace-config/src/useGardenDataSource.ts
- libs/shared/src/packages/workspace-config/src/useGridDataSource.ts
- libs/workorderapp/src/lib/config/gardenConfig.ts
- libs/workorderapp/src/lib/config/tableConfig.tsx
- libs/workorderapp/src/lib/config/workspace.tsx
> feat: :sparkles: improve access check

- libs/workorderapp/src/lib/ui-garden/Popover/PopoverContent.tsx
> fix(workorder): :bug: mccrstatus in workorder

- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/material/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/mccr/columns.tsx
- libs/shared/src/packages/workspace-config/src/defaultColDef.ts
- libs/workorderapp/src/lib/config/tableConfig.tsx
> chore: use discipline code and not discipline in table

- libs/loopapp/package.json
- libs/loopsidesheet/src/lib/ui-sidesheet/LoopSidesheet.tsx
- pnpm-lock.yaml
> feat: :sparkles: load loop from url

- libs/workorderapp/package.json
- libs/workordersidesheet/src/lib/ui-sidesheet/WorkorderSidesheet.tsx
- pnpm-lock.yaml
> feat: :sparkles: load workorder from url

- libs/loopapp/src/lib/config/tableConfig.tsx
- libs/punchapp/src/lib/config/tableConfig.tsx
- libs/shared/src/packages/workspace-config/src/useGridDataSource.ts
- libs/workorderapp/src/lib/config/tableConfig.tsx
Adds serverside grid sort for the following apps
> feat: :sparkles: grid sort for serverside apps

- libs/loopapp/package.json
- libs/loopapp/src/lib/config/gardenConfig.ts
- libs/loopapp/src/lib/config/statusBarConfig.ts
- libs/loopapp/src/lib/config/tableConfig.tsx
- libs/loopapp/src/lib/config/workspaceConfig.tsx
- libs/punchapp/package.json
- libs/punchapp/src/lib/config/gardenConfig.ts
- libs/punchapp/src/lib/config/statusBarConfig.ts
- libs/punchapp/src/lib/config/tableConfig.tsx
- libs/punchapp/src/lib/config/workspaceConfig.tsx
- libs/shared/package.json
- libs/shared/src/packages/workspace-config/src/useGardenDataSource.ts
- libs/shared/src/packages/workspace-config/src/useGridDataSource.ts
- libs/workorderapp/package.json
- libs/workorderapp/src/lib/config/gardenConfig.ts
- libs/workorderapp/src/lib/config/statusBarConfig.ts
- libs/workorderapp/src/lib/config/tableConfig.tsx
- libs/workorderapp/src/lib/config/workspace.tsx
- pnpm-lock.yaml
Adds search in filter to the following apps
> feat(serverside apps): filter search

- libs/handoversidesheet/src/lib/ui-sidesheet/HandoverSidesheet.tsx
- libs/mechanicalcompletionsidesheet/src/lib/types/mcNcr.ts
- libs/mechanicalcompletionsidesheet/src/lib/types/mcPunchItem.ts
- libs/mechanicalcompletionsidesheet/src/lib/types/mcWorkOrder.ts
- libs/mechanicalcompletionsidesheet/src/lib/ui-sidesheet/McSidesheet.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/mc/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/mc/types.ts
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/ncr/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/ncr/types.ts
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/punch/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/punch/type.ts
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/query/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/query/types.ts
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/swcr/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/swcr/types.ts
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/unsignedAction/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/unsignedAction/types.ts
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/unsignedTask/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/unsignedTask/types.ts
- libs/shared/src/packages/sidesheet/src/lib/stories/SidesheetTabs.stories.tsx
Added links to all identifiers in sidesheet for mc and handover
> feat: :sparkles: add pcs urls to handover and mc

- libs/punchapp/src/lib/config/tableConfig.tsx
Changed from true/false to Yes/No for material required column
> chore: update table config punch

- libs/handoverapp/package.json
- libs/handoverapp/src/lib/config/gardenConfig.ts
- libs/handoverapp/src/lib/config/sidesheetConfig.tsx
- libs/handoverapp/src/lib/config/tableConfig.tsx
- pnpm-lock.yaml
Bump Workspace dependency
Add more grid functionality like column pin, hide/show etc
> feat(handover): :sparkles: add more grid features

- libs/punchapp/package.json
- libs/punchapp/src/lib/config/gardenConfig.ts
- libs/punchapp/src/lib/config/sidesheetConfig.tsx
- libs/punchsidesheet/src/lib/ui-sidesheet/PunchSidesheet.tsx
- pnpm-lock.yaml
> chore: :arrow_up: upgrade workspace to v3 for punch

- cli/src/commands/release.ts
> fix: :bug: add project build for shipit procedure

- libs/workorderapp/package.json
- libs/workorderapp/src/lib/config/gardenConfig.ts
- libs/workorderapp/src/lib/config/sidesheetConfig.tsx
- libs/workorderapp/src/lib/ui-garden/Item.tsx
- pnpm-lock.yaml
migrate workorder to workspace v3
closes: #456
> feat:migrate workorder to workspace v3

- .github/workflows/pr-deploy.yml
- libs/handoverapp/package.json
- libs/loopapp/package.json
- libs/mechanicalcompletionapp/package.json
- libs/powerbiapp/package.json
- libs/powerbiapp/src/Report.tsx
- libs/punchapp/package.json
- libs/scopechangerequestapp/package.json
- libs/shared/package.json
- libs/shared/src/packages/workspace-config/src/useGardenDataSource.ts
- libs/swcrapp/package.json
- libs/workorderapp/package.json
- package.json
- pnpm-lock.yaml
Should retest all apps to be safe as this will affect ** every app and report **
> feat::sparkles: bump workspace v4

- libs/shared/src/packages/common/src/lib/NoContext.tsx
Sets a default context for the localhost instance of any app
> dx:default context selection for devs

- libs/shared/src/packages/workspace-config/src/useGardenDataSource.ts
- package.json
- pnpm-lock.yaml
Fixed a bug where outside click does not close the garden popover.
> fix(workspace): garden popover not closing on outside click

- .github/workflows/fprd-deploy.yml
- .github/workflows/pr-deploy.yml
- libs/handoversidesheet/package.json
- libs/loopsidesheet/package.json
- libs/mechanicalcompletionsidesheet/package.json
- libs/punchsidesheet/package.json
- libs/sharedcomponents/package.json
- libs/swcrsidesheet/package.json
- libs/workordersidesheet/package.json
- pnpm-lock.yaml
> ci: try fix ci prod deployment

- .github/workflows/manual-deploy.yml
Let's you manually deploy an app to test
> ci: :construction_worker: add manual deploy workflow for apps

- apps/handover/app.config.js
- libs/handoverapp/src/lib/config/gardenConfig.ts
- libs/handoverapp/src/lib/ui-garden/Item.tsx
- libs/handoverapp/src/lib/ui-garden/garden.styles.ts
- libs/handoversidesheet/src/lib/types.ts
- libs/handoversidesheet/src/lib/ui-sidesheet/HandoverSidesheet.tsx
- libs/shared/src/packages/common/src/lib/NoContext.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/ncr/columns.tsx
> Fix/ remaining issues to scale handover

- libs/handoversidesheet/src/lib/types.ts
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/mc/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/mc/types.ts
> fix mcpkg naming bug

- github-action/src/utils/uploadBundle.ts
Add a http call to ensure the app exists before uploading to fusion
> ci: ensure app exists

- package.json
- pnpm-lock.yaml
feat: Updated css for powerbi filters, making them more responsive
> chore: bump workspace@6.0.15

- libs/punchapp/src/lib/config/gardenConfig.ts
- libs/punchapp/src/lib/ui-garden/punchGardenItem.styles.ts
- libs/punchsidesheet/src/lib/ui-sidesheet/PunchSidesheet.tsx
https://miro.com/app/board/uXjVNM_KarU=/
> feat💄: punch finalize💅

- libs/shared/src/packages/fusion-framework/createRender.tsx
> fix: ignore powerbi generic error

- libs/mechanicalcompletionapp/src/lib/config/frameworkConfig.ts
add ag grid license to mc for JC
> chore: add license mc

- libs/punchapp/src/lib/config/tableConfig.tsx
Broken import resulted in Punch not being built in pipeline. Builds locally just fine. gnarly bug
> fix: punch build

- libs/heattracesidesheet/src/lib/ui-sidesheet/HeattraceSidesheet.tsx
Remove "Heat trace" and add status circle on "Checklist status"
> feat: :sparkles: change sidesheet banner

- libs/heattraceapp/src/lib/config/tableConfig.tsx
- package.json
- pnpm-lock.yaml
Updated @equinor/workspace-fusion to fix cramped-up filters.
fixes: equinor/cc-components#813
> 🐛 : Updated @equinor/workspace-fusion to fix cramped-up filters

- libs/heattraceapp/src/lib/config/tableConfig.tsx
- libs/shared/package.json
- libs/shared/src/packages/pbi-helpers/src/lib/error-component/AccessErrorComponent.tsx
- libs/shared/src/packages/pbi-helpers/src/lib/error-component/ErrorComponent.tsx
- libs/shared/src/packages/pbi-helpers/src/lib/error-component/accessErrorComponentStyles.ts
- libs/shared/src/packages/pbi-helpers/src/lib/usePBIOptions.tsx
- libs/shared/src/packages/pbi-helpers/src/lib/useReportErrorInfo.ts
- package.json
- pnpm-lock.yaml
Created new component for handling 401 and 403 access errors
Added new hook for fetching error-related info from report API.
Implements: equinor/fusion-workspace#551
> 🎁: Implemented report access-information fetcing

- libs/pipingapp/src/lib/config/workspaceConfig.tsx
Added PBI report to Pipetest app.
Issue: equinor/cc-components#461
> ✨ Added PBI to Pipetest

- libs/loopapp/src/lib/config/frameworkConfig.ts
Configuring ag grid license specifically for Castberg portal where apps are responsible for adding licenses themselves
> add loop ag grid license

- README.md
> docs: documenting fusion app management

- README.md
Update readme. Add "Project and app structure" chapter
Link to issue: https://github.com/equinor/cc-components/issues/909
> [!TIP]
> [!CAUTION]
> chore: :memo: Update readme. Add project and app structure

- README.md
Repository is Equinor SCM compliant
Link to issue:
> [!TIP]
> [!CAUTION]
> chore: Added SCM badge

- CONTRIBUTING.md
- README.md
Link to issue: https://github.com/equinor/lighthouse/issues/550
> [!TIP]
> [!CAUTION]
> 🎁 Repos are Equinor SCM compliant

- libs/heattracesidesheet/src/lib/ui-sidesheet/HeattraceSidesheet.tsx
- libs/pipingsidesheet/src/lib/ui-sidesheet/ElectricalNetworkTab.tsx
- libs/pipingsidesheet/src/lib/utils-sidesheet/useElectricalNetwork.ts
Migrated ele networks endpoint to use FDG instead of eleconsumers
> chore: migrate eleconsumers endpoint

- apps/punch/app.config.js
- apps/punch/app.config.local.js
- apps/punch/tsconfig.app.json
- apps/punch/vite.config.ts
- libs/modelviewer/src/components/tag-info/TagInfo.tsx
- libs/modelviewer/src/components/tag-item/TagItem.tsx
- libs/modelviewer/src/hooks/useModelTags.ts
- libs/modelviewer/src/hooks/useOverlay.ts
- libs/modelviewer/src/providers/tagSelectionProvider.tsx
- libs/punchapp/package.json
- libs/punchapp/src/lib/config/frameworkConfig.ts
- libs/punchsidesheet/package.json
- libs/punchsidesheet/src/lib/ui-sidesheet/PunchSidesheet.tsx
- libs/punchsidesheet/src/lib/utils-sidesheet/useModelViewerTags.tsx
- patches/3d-patch.ts
- pnpm-lock.yaml
Added modelviewer to punch sidesheet.
Added tooltip do view full descriptions when clicking info-button in modelviewer tags.
Link to issue: https://github.com/equinor/cc-components/issues/582
> [!TIP]
> [!CAUTION]
> 🎁 [punch]: Enable 3D in sidesheet

- libs/pipingapp/src/lib/utils-garden/getPipetestStatusColors.ts
- libs/pipingapp/src/lib/utils-garden/getTextColor.ts
Pipetest - Fix vertical sorting in garden. Change to correct colors. 
Link to issue: https://github.com/equinor/cc-components/issues/955
> [!TIP]
> [!CAUTION]
> fix: :bug: Pipetest - fix vertical sorting in garden

- libs/shared/src/packages/error-boundary/src/components/AppErrorBoundary.tsx
- libs/shared/src/packages/error-boundary/src/components/errors/UnknownError.tsx
Added styled error message of unknown errors.
Added console output of such errors.
Link to issue: No issue
> [!TIP]
> [!CAUTION]
> 🎁 Added styled error message for unknown errors

- README.md
Added Onboarding section to README
Link to issue: https://github.com/equinor/lighthouse/issues/539
> [!TIP]
> [!CAUTION]
> :scroll: Onboarding section to README

- libs/handovershared/src/lib/types/handoverPackage.ts
- libs/handoversidesheet/src/lib/ui-sidesheet/DetailsTabs.tsx
Added description of work to handover sidesheet
Link to issue:
https://github.com/orgs/equinor/projects/415/views/7?pane=issue&itemId=59769099
> [!TIP]
> [!CAUTION]
> feat(handover): Add description of work to handover

- .github/workflows/fprd-deploy.yml
- .github/workflows/pr-deploy.yml
- package.json
Fixed turbo scripts after turbo package update.
Link to issue: https://github.com/equinor/lighthouse/issues/554
> [!TIP]
> [!CAUTION]
> fix: turbo scripts

- apps/heattrace/vite.config.ts
- apps/loop/tsconfig.app.json
- apps/loop/vite.config.ts
- apps/scopechangerequest/vite.config.ts
- apps/swcr/tsconfig.app.json
- apps/swcr/vite.config.ts
Hotfix to issue introducted by fusion-framework as part of dependency bump.
Added process plugin to apps.
Link to issue: https://github.com/equinor/lighthouse/issues/554
> [!TIP]
> [!CAUTION]
> 🚑 hotfix: Process plugin

- .github/workflows/fprd-deploy.yml
- apps/handover/src/main.tsx
Link to issue:
> [!TIP]
> [!CAUTION]
> fix: auto deploy FPRD trigger in turbo

- libs/handoverapp/src/lib/config/workspaceConfig.tsx
- libs/heattraceapp/src/lib/config/workspaceConfig.tsx
- libs/loopapp/src/lib/config/workspaceConfig.tsx
- libs/mechanicalcompletionapp/src/lib/config/workspaceConfig.tsx
- libs/pipingapp/src/lib/config/workspaceConfig.tsx
- libs/punchapp/src/lib/config/workspaceConfig.tsx
- libs/scopechangerequestapp/src/lib/config/workspaceConfig.tsx
- libs/shared/src/packages/hooks/src/lib/index.ts
- libs/shared/src/packages/hooks/src/lib/useCloseSidesheetOnContextChanges.ts
- libs/swcrapp/src/lib/config/workspaceConfig.tsx
- libs/workorderapp/src/lib/config/workspace.tsx
Add a hook for closing sidesheet when context id changes
> fix: close sidesheet when context changes

- .github/actions/pnpm-setup/action.yaml
- libs/handoverapp/src/lib/config/tableConfig.tsx
- libs/heattraceapp/src/lib/config/tableConfig.tsx
- libs/mechanicalcompletionapp/src/lib/config/tableConfig.tsx
- libs/pipingapp/src/lib/config/tableConfig.tsx
- libs/punchapp/src/lib/config/tableConfig.tsx
- libs/scopechangerequestapp/src/lib/config/tableConfig.tsx
- libs/shared/src/packages/workspace-config/src/defaultGridOptions.tsx
- libs/shared/src/packages/workspace-config/src/useGridDataSource.ts
- libs/swcrapp/src/lib/config/tableConfig.tsx
Updated AG-Grid to use the new api to remove deprecation warnings
Link to issue:
https://github.com/equinor/fusion-workspace/issues/631
> [!TIP]
> [!CAUTION]
> fix: :bug: Updated AG-Grid to use the new api to remove deprecation warnings

- libs/punchapp/src/lib/config/tableConfig.tsx
> fix: duplicate punch column formType, add PL priority

- package.json
- pnpm-lock.yaml
Update workspace to 9.0.10 to include KPI changes
Link to issue:
https://github.com/equinor/cc-components/issues/1035
> [!TIP]
> [!CAUTION]
> feat: Update workspace to 9.0.10

- libs/shared/src/packages/cc-api/useCCApiAccessCheck.ts
> feat: improve error messages on 5xx status codes

- libs/heattraceshared/src/lib/types/heatTraceHeatedTag.ts
- libs/heattraceshared/src/lib/types/index.ts
- libs/heattracesidesheet/src/lib/ui-sidesheet/HeatedTagsTab.tsx
- libs/heattracesidesheet/src/lib/ui-sidesheet/HeattraceSidesheet.tsx
- libs/heattracesidesheet/src/lib/ui-sidesheet/heatedTagsColumns.tsx
- libs/heattracesidesheet/src/lib/utils-sidesheet/useGetHeatedTags.ts
Added new tab for Heated tags in HeatTrace app.
Link to issue: https://github.com/equinor/cc-components/issues/827
> [!TIP]
> [!CAUTION]
> 🎁 Heated-tags tab in HeatTrace app

- libs/handoversidesheet/src/lib/types.ts
- libs/handoversidesheet/src/lib/ui-sidesheet/HandoverSidesheet.tsx
- libs/loopsidesheet/src/lib/utils-sidesheet/useGetWorkorders.ts
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/workorder/columns.tsx
- libs/shared/src/packages/sidesheet/src/lib/sidesheet/tabs/workorder/types.ts
Had to update some column types etc to accomodate backend changes
> feat: handover workorders tab

- libs/handoverapp/src/lib/ui-garden/PopoverContent.tsx
- libs/heattraceapp/src/lib/ui-garden/Item.tsx
- libs/heattraceapp/src/lib/ui-garden/garden.styles.ts
- libs/loopapp/src/lib/ui-garden/Popover.tsx
- libs/mechanicalcompletionapp/src/lib/ui-garden/Popover/PopoverContent.tsx
- libs/shared/src/packages/common/src/lib/StatusCircle.tsx
- libs/shared/src/packages/common/src/lib/popover/popover.styles.ts
- libs/shared/src/packages/table-helpers/src/lib/table/cells/EstimateCell.tsx
- libs/shared/src/packages/table-helpers/src/lib/table/cells/ProgressCell.tsx
- libs/shared/src/packages/table-helpers/src/lib/table/cells/cell.styles.ts
- libs/sharedcomponents/src/packages/sidesheet/Banner/banner.styles.ts
- libs/sharedcomponents/src/packages/sidesheet/Header/Header.tsx
- libs/swcrapp/src/lib/config/gardenConfig.tsx
- libs/swcrapp/src/lib/ui-garden/Item.tsx
- libs/swcrapp/src/lib/ui-garden/garden.styles.ts
- libs/swcrsidesheet/src/lib/ui-sidesheet/DetailsTab.tsx
- libs/swcrsidesheet/src/lib/ui-sidesheet/SwcrSidesheet.tsx
- libs/swcrsidesheet/src/lib/utils-sidesheet/useSignatures.ts
- libs/workorderapp/src/lib/ui-garden/Popover/PopoverContent.tsx
Updated swcr sidesheet 
Also made some styled-components changes from the v6 update, all propes should be prefixed with $.
> feat: swcr scaling improvements

- libs/shared/src/packages/fusion-framework/createRender.tsx
Remove potential xss from unused feature
Link to issue:
https://github.com/equinor/cc-components/issues/1063
> [!TIP]
> [!CAUTION]
> chore: Remove potential xss

- package.json
- pnpm-lock.yaml
Updates workspace-fusion to 9.0.11 to use the new KPI bar
Link to issue:
https://github.com/equinor/cc-components/issues/1035
> [!TIP]
> [!CAUTION]
> chore: Update workspace-fusion dependency to version 9.0.11

- apps/heattrace/src/main.tsx
> fix(ht): logging as unknown in usage report

- libs/heattraceapp/src/lib/config/gardenConfig.tsx
Heat trace garden less space between items
Link to issue:
https://github.com/equinor/cc-components/issues/854
> [!TIP]
> [!CAUTION]
Closes #854
> 854 heat trace garden less space between items

- libs/pipingsidesheet/src/lib/ui-sidesheet/checklistColumns.tsx
Update pipetest checklist sidesheet to render checklist revision correctly
Link to issue:
https://github.com/equinor/cc-components/issues/1055
> [!TIP]
> [!CAUTION]
Closes #1055
> chore: Update checklistColumns.tsx to fix cell rendering

- package.json
- pnpm-lock.yaml
Update workspace-fusion dependency to version 9.0.12
> [!TIP]
> [!CAUTION]
> chore: Update workspace-fusion dependency to version 9.0.12

- package.json
- pnpm-lock.yaml
Update workspace-fusion dependency to version 9.0.13
> [!TIP]
> [!CAUTION]
> chore: Update workspace-fusion dependency to version 9.0.13

- package.json
- pnpm-lock.yaml
bump workspace version
Link to issue:
> [!TIP]
> [!CAUTION]
> Chore: bump workspace version

- libs/handoverapp/src/lib/config/workspaceConfig.tsx
- libs/heattraceapp/src/lib/config/frameworkConfig.ts
- libs/heattraceapp/src/lib/config/workspaceConfig.tsx
- libs/loopapp/src/lib/config/frameworkConfig.ts
- libs/loopapp/src/lib/config/workspaceConfig.tsx
- libs/pipingapp/src/lib/config/frameworkConfig.ts
- libs/pipingapp/src/lib/config/workspaceConfig.tsx
- libs/punchapp/src/lib/config/frameworkConfig.ts
- libs/punchapp/src/lib/config/workspaceConfig.tsx
- libs/swcrapp/src/lib/config/frameworkConfig.ts
- libs/swcrapp/src/lib/config/workspaceConfig.tsx
- libs/workorderapp/src/lib/config/frameworkConfig.ts
- libs/workorderapp/src/lib/config/workspace.tsx
Added support for facilities in PBI and apps
Link to issue: https://github.com/equinor/lighthouse/issues/651
> [!TIP]
> [!CAUTION]
> :gift: Enabled Facilities for Punch, Loop, Pipetest, HeatTrace, Workorder and SWCR

- libs/mechanicalcompletionapp/src/lib/config/frameworkConfig.ts
- libs/mechanicalcompletionapp/src/lib/config/workspaceConfig.tsx
Enabled facility for MC and PBI
Link to issue: https://github.com/equinor/lighthouse/issues/671
> [!TIP]
> [!CAUTION]
> :gift: Added facility support for MC

- libs/workordersidesheet/src/lib/types/index.ts
- libs/workordersidesheet/src/lib/types/workOrderNotification.ts
- libs/workordersidesheet/src/lib/ui-sidesheet/WorkorderSidesheet.tsx
- libs/workordersidesheet/src/lib/utils-sidesheet/useNotifications.ts
Added notifications to WorkOrder sidesheet.
Link to issue: https://github.com/equinor/cc-components/issues/384
> [!TIP]
> [!CAUTION]
> 🎁 WorkOrder Notifications

- libs/workordersidesheet/src/lib/types/index.ts
- libs/workordersidesheet/src/lib/types/workOrderDescription.ts
- libs/workordersidesheet/src/lib/ui-sidesheet/DetailsTab.tsx
- libs/workordersidesheet/src/lib/ui-sidesheet/WorkorderDescription.tsx
- libs/workordersidesheet/src/lib/utils-sidesheet/useWorkOrderDescription.ts
Added workorder description to workorder sidesheet.
Link to issue: https://github.com/equinor/lighthouse/issues/346
> [!TIP]
> [!CAUTION]
> 🎁 Workorder description field
